services:
  wsclient:
    image: wsclient:latest
    build:
      context: .  # Specify the build context (current directory)
      dockerfile: Dockerfile  # Specify the Dockerfile if it's named differently
    hostname: wsclient
    working_dir: /usr/src/wsclient
    volumes: [ .:/usr/src/wsclient ]
    command: go run github.com/qwertydi/go-challenge
    mem_limit: 4096MB
    networks: [ playground ]
    environment:
      SOCKET_HOST: wsserver
      SOCKET_PORT: 5050

  wsserver:
    image: public.ecr.aws/h0f1y5l9/wsserver:latest
    hostname: wsserver
    mem_limit: 4096MB
    ports: [ '5050:5050' ]
    networks: [ playground ]

networks:
  playground:
    name: playground
